// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzcwpkkssumterchpqnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6Y3dwa2tzc3VtdGVyY2hwcW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5Njk5OTksImV4cCI6MjA3NDU0NTk5OX0.nZqfx8Y87Fep3LiaPJ3Jg23TsIDSHVpD84IVZaMUY_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});